var Listado = [
    //Estanteria Nivel 1
    { "id": 1, "nombre": "2", "img": "./assets/productos/2.png", "x": 25, "y":estante1, puntos:0 },
    { "id": 2, "nombre": "foto", "img": "./assets/productos/foto.png", "x": 90, "y":estante1, puntos:1 },
    { "id": 3, "nombre": "10", "img": "./assets/productos/5.png", "x": 170, "y":estante1, puntos:0 },
    { "id": 4, "nombre": "foto", "img": "./assets/productos/foto.png", "x": 250, "y":estante1, puntos:1 },
    { "id": 5, "nombre": "12", "img": "./assets/productos/6.png", "x": 320, "y":estante1, puntos:0 },    
    { "id": 6, "nombre": "foto2", "img": "./assets/productos/foto.png", "x": 390, "y":estante1, puntos:1 },
    { "id": 7, "nombre": "1", "img": "./assets/productos/1.png", "x": 460, "y":estante1, puntos:0 },
    { "id": 8, "nombre": "Nesquick", "img": "./assets/productos/foto.png", "x": 540, "y":estante1, puntos:1 },    
    { "id": 9, "nombre": "15", "img": "./assets/productos/7.png", "x": 630, "y":estante1, puntos:0 },    
    { "id": 10, "nombre": "3", "img": "./assets/productos/3.png", "x": 710, "y":estante1, puntos:0 },
    { "id": 11, "nombre": "foto", "img": "./assets/productos/foto.png", "x": 770, "y":estante1, puntos:1 },
    { "id": 12, "nombre": "13", "img": "./assets/productos/4.png", "x": 870, "y":estante1, puntos:0 },
    { "id": 13, "nombre": "foto2", "img": "./assets/productos/foto.png", "x": 950, "y":estante1, puntos:1 },
    //Estanteria Nivel 2
    { "id": 14, "nombre": "2", "img": "./assets/productos/2.png", "x": 25, "y":estante2, puntos:0 },
    { "id": 15, "nombre": "foto", "img": "./assets/productos/foto.png", "x": 90, "y":estante2, puntos:1 },
    { "id": 16, "nombre": "10", "img": "./assets/productos/5.png", "x": 170, "y":estante2, puntos:0 },
    { "id": 17, "nombre": "foto", "img": "./assets/productos/foto.png", "x": 250, "y":estante2, puntos:1 },
    { "id": 18, "nombre": "12", "img": "./assets/productos/6.png", "x": 320, "y":estante2, puntos:0 },    
    { "id": 19, "nombre": "foto2", "img": "./assets/productos/foto.png", "x": 390, "y":estante2, puntos:1 },
    { "id": 20, "nombre": "1", "img": "./assets/productos/1.png", "x": 460, "y":estante2, puntos:0 },
    { "id": 21, "nombre": "Nesquick", "img": "./assets/productos/foto.png", "x": 540, "y":estante2, puntos:1 },    
    { "id": 22, "nombre": "15", "img": "./assets/productos/7.png", "x": 630, "y":estante2, puntos:0 },    
    { "id": 23, "nombre": "3", "img": "./assets/productos/3.png", "x": 710, "y":estante2, puntos:0 },
    { "id": 24, "nombre": "foto", "img": "./assets/productos/foto.png", "x": 770, "y":estante2, puntos:1 },
    { "id": 25, "nombre": "13", "img": "./assets/productos/4.png", "x": 870, "y":estante2, puntos:0 },
    { "id": 26, "nombre": "foto2", "img": "./assets/productos/foto.png", "x": 950, "y":estante2, puntos:1 },
    //Estanteria Nivel 3
    { "id": 27, "nombre": "2", "img": "./assets/productos/2.png", "x": 25, "y":estante3, puntos:0 },
    { "id": 28, "nombre": "foto", "img": "./assets/productos/foto.png", "x": 90, "y":estante3, puntos:1 },
    { "id": 29, "nombre": "10", "img": "./assets/productos/5.png", "x": 170, "y":estante3, puntos:0 },
    { "id": 30, "nombre": "foto", "img": "./assets/productos/foto.png", "x": 250, "y":estante3, puntos:1 },
    { "id": 31, "nombre": "12", "img": "./assets/productos/6.png", "x": 320, "y":estante3, puntos:0 },    
    { "id": 32, "nombre": "foto2", "img": "./assets/productos/foto.png", "x": 390, "y":estante3, puntos:1 },
    { "id": 33, "nombre": "1", "img": "./assets/productos/1.png", "x": 460, "y":estante3, puntos:0 },
    { "id": 34, "nombre": "Nesquick", "img": "./assets/productos/foto.png", "x": 540, "y":estante3, puntos:1 },    
    { "id": 35, "nombre": "15", "img": "./assets/productos/7.png", "x": 630, "y":estante3, puntos:0 },    
    { "id": 36, "nombre": "3", "img": "./assets/productos/3.png", "x": 710, "y":estante3, puntos:0 },
    { "id": 37, "nombre": "foto", "img": "./assets/productos/foto.png", "x": 770, "y":estante3, puntos:1 },
    { "id": 38, "nombre": "13", "img": "./assets/productos/4.png", "x": 870, "y":estante3, puntos:0 },
    { "id": 39, "nombre": "foto2", "img": "./assets/productos/foto.png", "x": 950, "y":estante3, puntos:1 },
    //Estanteria Nivel 4
    { "id": 40, "nombre": "2", "img": "./assets/productos/2.png", "x": 25, "y":estante4, puntos:0 },
    { "id": 41, "nombre": "foto", "img": "./assets/productos/foto.png", "x": 90, "y":estante4, puntos:1 },
    { "id": 42, "nombre": "10", "img": "./assets/productos/5.png", "x": 170, "y":estante4, puntos:0 },
    { "id": 43, "nombre": "foto", "img": "./assets/productos/foto.png", "x": 250, "y":estante4, puntos:1 },
    { "id": 44, "nombre": "12", "img": "./assets/productos/6.png", "x": 320, "y":estante4, puntos:0 },    
    { "id": 45, "nombre": "foto2", "img": "./assets/productos/foto.png", "x": 390, "y":estante4, puntos:1 },
    { "id": 46, "nombre": "1", "img": "./assets/productos/1.png", "x": 460, "y":estante4, puntos:0 },
    { "id": 47, "nombre": "Nesquick", "img": "./assets/productos/foto.png", "x": 540, "y":estante4, puntos:1 },    
    { "id": 48, "nombre": "15", "img": "./assets/productos/7.png", "x": 630, "y":estante4, puntos:0 },    
    { "id": 49, "nombre": "3", "img": "./assets/productos/3.png", "x": 710, "y":estante4, puntos:0 },
    { "id": 50, "nombre": "foto", "img": "./assets/productos/foto.png", "x": 770, "y":estante4, puntos:1 },
    { "id": 51, "nombre": "13", "img": "./assets/productos/4.png", "x": 870, "y":estante4, puntos:0 },
    { "id": 52, "nombre": "foto2", "img": "./assets/productos/foto.png", "x": 950, "y":estante4, puntos:1 },
  ]
